driving/urls.py
from django.urls import path
from driving import views

app_name = 'driving'
urlpatterns = [
    path('', views.driving_index, name='driving_index'),
]

weekenddestpy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

import driving  # 追加

urlpatterns = [
    path('driving/', include('driving.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/driving')),  # ルート
]

driving/models.py
from django.db import models

# Create your models here.


class Src(models.Model):
    src = models.CharField('出発地', max_length=255)


class Dest(models.Model):
    name = models.CharField('名称', max_length=255)
    latitude = models.CharField('北緯', max_length=255)
    longitude = models.CharField('東経', max_length=255)
    address = models.CharField('所在地', max_length=255)


class geoCash(models.Model):
    src = models.CharField('出発地', max_length=255)
    latitude = models.CharField('北緯', max_length=255)
    longitude = models.CharField('東経', max_length=255)


class routeCash(models.Model):
    src = models.CharField('出発地', max_length=255)
    dest = models.CharField('目的地', max_length=255)
    highway = models.CharField('高速', max_length=255)
    localway = models.CharField('下道', max_length=255)

driving/forms.py
from turtle import distance
from django import forms
from django.forms import ModelForm

from driving.models import Src


class SrcForm(forms.Form):
    """出発地のフォーム"""
    src = forms.CharField(label='出発地', max_length=255, required=True,
                          widget=forms.TextInput(
                              attrs={'placeholder': '名称、座標どちらでも可', 'class': 'form-control col-xl'}))
    distance = forms.IntegerField(label='所要時間', required=True, widget=forms.TextInput(
        attrs={'type': 'number', 'class': 'form-control col-3', 'list': 'distanceList', 'value': '30', 'min': '1'}))

driving/views.py
import logging
from unittest import skip
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from driving.forms import SrcForm
from driving.models import Dest, Src, geoCash, routeCash
from geopy.distance import geodesic
import random

from driving.utils.geo import Geo
from driving.utils.route import Route
from driving.utils.wiki import Wiki
from django.contrib import messages

# Create your views here.


@require_http_methods(['GET'])
def driving_index(request):
    """検索画面"""

    params = {
        'form': SrcForm(request.GET or None),
    }

    if "src" in request.GET and "distance" in request.GET:
        # 出発地が設定されている場合
        srcParam = request.GET.get("src")
        distanceParam = int(request.GET.get("distance"))
        src = []
        # 検索したことがある場所ならcashから取得

        geocash = geoCash.objects.filter(src=srcParam).first()
        if geocash is not None:
            src.append(geocash.latitude)
            src.append(geocash.longitude)
        else:
            try:
                geo = Geo().getGeo(srcParam)
            except:
                messages.error(request, "場所が特定できません")
                return render(request,
                      'driving/index.html', params)
           
            src.append(str(geo["result"]["latitude"]))
            src.append(str(geo["result"]["longitude"]))
            geoCash.objects.create(
                src=srcParam, latitude=geo["result"]["latitude"], longitude=geo["result"]["longitude"])

        randomDest = []
        for d in Dest.objects.all():
            dis = geodesic((float(src[0]), float(src[1])),
                           (float(d.latitude), float(d.longitude))).km
            if dis <= distanceParam and dis >= distanceParam * 0.9:
                randomDest.append(d)

        if not randomDest:
            # 空ならすべてからランダムにする
            for d in Dest.objects.all():
                randomDest.append(d)
                
        # ランダムに１つ選ぶ
        choiced = random.choice(randomDest)

        routecashmodel = routeCash.objects.filter(
            src=src[0] + "," + src[1], dest=choiced.latitude + "," + choiced.longitude).first()

        if routecashmodel is not None:
            params = dict(
                name=choiced.name, src=src[0] + "," + src[1], dest=choiced.latitude + "," + choiced.longitude, highway=routecashmodel.highway, localway=routecashmodel.localway)
        else:
            try:
                route = Route().getRoute(
                [dict(src=srcParam, dest=choiced.latitude + "," + choiced.longitude, place_name=choiced.name)])
                params = dict(
                name=choiced.name, src=src[0] + "," + src[1], dest=choiced.latitude + "," + choiced.longitude, highway=route["result"][0]["distance"]["highway"], localway=route["result"][0]["distance"]["localway"])
                routeCash.objects.create(src=src[0] + "," + src[1], dest=choiced.latitude + "," + choiced.longitude,
                                     highway=route["result"][0]["distance"]["highway"], localway=route["result"][0]["distance"]["localway"])
            finally:
                # 距離計算のAPIがエラーの場合は何も出さない
                pass
                

        wikiSumally = Wiki().getWiki(choiced.name)

        params["wiki"] = wikiSumally if wikiSumally is not None else ""

        return render(request,
                      'driving/list.html', params)
    else:
        # それ以外
        return render(request,
                      'driving/index.html', params)

templates/base.html
{% load i18n static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="icon" type="image/png" href="{% static 'icon/favicon.png' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}{% endblock %}</title>
</head>
<body>
  <div class="container">
    <div class="mt-2">
    {% for message in messages %}
    <div {% if message.tags %}class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
  </div>
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
{% block extra_js %}{% endblock %}
</body>
</html>

templates/driving/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
    週末どこ行く
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="mt-5 mb-5 display-1 kiwi_font">週末どこ行く？</div>
        <form action="{% url 'driving:driving_index' %}" method="get">
            <div class="input-group col-md-auto mb-3">
                <span class="input-group-text kiwi_font" id="basic-addon1">出発地</span>
                {{ form.src }}
                <button class="btn btn-primary kiwi_font" type="button" id="geoBtn">現在地取得</button>
            </div>
            <div class="input-group col-md-auto mb-3">
                <span class="input-group-text kiwi_font" id="basic-addon1">片道の距離(km)</span>
                {{ form.distance }}
                <datalist id="distanceList">
                    <option value="30"></option>
                    <option value="50"></option>
                    <option value="100"></option>
                    <option value="200"></option>
                    <option value="300"></option>
                    <option value="400"></option>
                    <option value="500"></option>
                    </datalist>
            </div>
            <div class="d-grid gap-2 col-6 mx-auto">
                <input type="submit" value="出発" class="kiwi_font btn btn-primary"/>
            </div>
        </form>
    </div>
    <script>
        $('#geoBtn').on('click', function() {
          navigator.geolocation.getCurrentPosition(function(pos){
            $("#id_src").val(pos.coords.latitude + "," + pos.coords.longitude)
          },function(){
      
          });
        });
    </script>
{% endblock content %}

templates/driving/list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
    週末どこ行く
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="mt-5 mb-5 display-1 kiwi_font">週末ここ行こう！</div>
        <div class="mx-5">
            <div class="py-2">
                <div class="card">
                    <div class="card-header display-5 kiwi_font">
                        <li>{{ name }}</li>
                    </div>
                    <div class="card-body pt-5 bg-light">
                        <figure>
                            <iframe src="https://maps.google.com/maps?output=embed&ll={{ dest }}&t=m&hl=ja&z=15"
                                    width="100%"
                                    height="250"
                                    frameborder="0"
                                    style="border:0;"
                                    allowfullscreen=""></iframe>
                            <figcaption class="blockquote-footer">
                                <p>{{ wiki }}</p>
                            </figcaption>
                        </figure>
                        <blockquote class="blockquote pt-1 kiwi_font">
                            <p>高速で{{ highway }}km</p>
                        </blockquote>
                        <blockquote class="blockquote mb-0 kiwi_font">
                            <p>下道で{{ localway }}km</p>
                        </blockquote>
                        <div class="col mt-5 display-5 kiwi_font ta-r">
                            <a href="https://www.google.co.jp/maps/dir/{{ src }}/{{ dest }}/data=!4m3!4m2!3e0!4e0"
                               target="_blank">ルート検索</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="kiwi_font">
                <a href="{% url 'driving:driving_index' %}">戻る</a>
            </div>
        </div>
    </div>
{% endblock content %}